# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='the_title',
        ),
    ]
